app = "sms-rate-limiter"
primary_region = "yyz"  # Toronto region, you can change this

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.ports]]
  port = 80
  handlers = ["http"]

[[http_service.ports]]
  port = 443
  handlers = ["tls", "http"]

[env]
  ASPNETCORE_ENVIRONMENT = "Production" 